# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ashley Jones | UX Portolio
email: ashley.m.jones14@gmail.com
description: Portfolio of Ashley Jones
baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
permalink: /:categories/:title
sass:
  sass_dir: css

contentful:
  spaces:
    - example: # Jekyll _data folder identifier - Required
        space: 2k1pbhdkfamn
        access_token: 344caef86ce876792ddb616f0a0321126a805babc64c05e85fb02300b6bb89ca

page_gen:
  - data: 'contentful.spaces.example.news'
    template: 'post'
    name: 'url'
    dir: 'news'
  - data: 'contentful.spaces.example.practiceBlog'
    template: 'blogpost'
    name: 'url'
    dir: 'blog'

google_api_key: AIzaSyAfVmbEceIsXob264XZynAYwqVbF0f7QR4
